name: Release

permissions:
  contents: write

on:
  push:
    tags:
      - v[0-9]+\.[0-9]+\.[0-9]+
  workflow_dispatch:
    inputs:
      tag:
        description: 'Release tag (e.g., v1.0.0)'
        required: true

jobs:
  create-release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: taiki-e/create-gh-release-action@v1
        with:
          changelog: CHANGELOG.md
          token: ${{ secrets.GITHUB_TOKEN }}

  upload-assets:
    needs: create-release
    strategy:
      matrix:
        include:
          - target: x86_64-pc-windows-gnu
            os: ubuntu-latest
          - target: x86_64-unknown-linux-gnu
            os: ubuntu-latest
    runs-on: ${{ matrix.os }}
    env:
      CROSS_TARGET_IMAGE: ghcr.io/cross-rs/${{ matrix.target }}:main-openssl
    steps:
      - uses: actions/checkout@v4

      - name: Install Rust toolchain
        run: rustup update stable

      - name: Install cross-compilation tools
        uses: taiki-e/setup-cross-toolchain-action@v1
        with:
          target: ${{ matrix.target }}

      - name: Install cross
        run: cargo install cross --git https://github.com/cross-rs/cross

      - uses: taiki-e/upload-rust-binary-action@v1
        with:
          bin: shepherd
          target: ${{ matrix.target }}
          build-tool: cross
          token: ${{ secrets.GITHUB_TOKEN }}

